/*
  # Add Invite Code System for Business Onboarding
  
  ## Overview
  Implements a simplified invite code system for team onboarding.
  Replaces complex email-based invitations with shareable codes.
  
  ## Changes
  1. Add invite_code column to businesses table
    - Short, unique 8-character alphanumeric code
    - Generated automatically on business creation
    - Can be regenerated by captain
  
  2. Add public function to accept invite codes
    - Validates code and business existence
    - Adds user to business_members as 'viewer' by default
    - Prevents duplicate memberships
  
  3. Security
    - Only authenticated users can join via invite code
    - Users automatically added as 'viewer' role
    - Captain can change roles after joining
    - Prevents users from joining same business twice
  
  ## Notes
  - Invite codes are permanent (don't expire)
  - Captain can regenerate code to revoke old one
  - Simple 8-character format: ABCD1234
*/

-- ============================================================================
-- ADD INVITE CODE TO BUSINESSES TABLE
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'businesses' AND column_name = 'invite_code'
  ) THEN
    ALTER TABLE businesses ADD COLUMN invite_code text UNIQUE;
  END IF;
END $$;

-- ============================================================================
-- FUNCTION TO GENERATE RANDOM INVITE CODE
-- ============================================================================

CREATE OR REPLACE FUNCTION generate_invite_code()
RETURNS text AS $$
DECLARE
  chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result text := '';
  i integer;
BEGIN
  FOR i IN 1..8 LOOP
    result := result || substr(chars, floor(random() * length(chars) + 1)::integer, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- FUNCTION TO AUTO-GENERATE INVITE CODE ON BUSINESS CREATION
-- ============================================================================

CREATE OR REPLACE FUNCTION set_business_invite_code()
RETURNS TRIGGER AS $$
DECLARE
  new_code text;
  code_exists boolean;
BEGIN
  IF NEW.invite_code IS NULL THEN
    LOOP
      new_code := generate_invite_code();
      SELECT EXISTS(SELECT 1 FROM businesses WHERE invite_code = new_code) INTO code_exists;
      EXIT WHEN NOT code_exists;
    END LOOP;
    NEW.invite_code := new_code;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_invite_code_trigger ON businesses;
CREATE TRIGGER set_invite_code_trigger
  BEFORE INSERT ON businesses
  FOR EACH ROW
  EXECUTE FUNCTION set_business_invite_code();

-- ============================================================================
-- GENERATE CODES FOR EXISTING BUSINESSES
-- ============================================================================

DO $$
DECLARE
  business_record RECORD;
  new_code text;
  code_exists boolean;
BEGIN
  FOR business_record IN SELECT id FROM businesses WHERE invite_code IS NULL LOOP
    LOOP
      new_code := generate_invite_code();
      SELECT EXISTS(SELECT 1 FROM businesses WHERE invite_code = new_code) INTO code_exists;
      EXIT WHEN NOT code_exists;
    END LOOP;
    UPDATE businesses SET invite_code = new_code WHERE id = business_record.id;
  END LOOP;
END $$;

-- ============================================================================
-- FUNCTION TO JOIN BUSINESS VIA INVITE CODE
-- ============================================================================

CREATE OR REPLACE FUNCTION join_business_with_code(code text)
RETURNS jsonb AS $$
DECLARE
  business_record RECORD;
  already_member boolean;
  result jsonb;
BEGIN
  SELECT id, name INTO business_record
  FROM businesses
  WHERE invite_code = code;
  
  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Invalid invite code'
    );
  END IF;
  
  SELECT EXISTS(
    SELECT 1 FROM business_members
    WHERE business_id = business_record.id
    AND user_id = auth.uid()
  ) INTO already_member;
  
  IF already_member THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'You are already a member of this business'
    );
  END IF;
  
  INSERT INTO business_members (business_id, user_id, role)
  VALUES (business_record.id, auth.uid(), 'viewer');
  
  RETURN jsonb_build_object(
    'success', true,
    'business_id', business_record.id,
    'business_name', business_record.name
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- FUNCTION TO REGENERATE INVITE CODE (CAPTAIN ONLY)
-- ============================================================================

CREATE OR REPLACE FUNCTION regenerate_invite_code(business_id uuid)
RETURNS jsonb AS $$
DECLARE
  new_code text;
  code_exists boolean;
  is_owner boolean;
BEGIN
  SELECT EXISTS(
    SELECT 1 FROM businesses
    WHERE id = business_id
    AND owner_id = auth.uid()
  ) INTO is_owner;
  
  IF NOT is_owner THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Only the captain can regenerate invite codes'
    );
  END IF;
  
  LOOP
    new_code := generate_invite_code();
    SELECT EXISTS(SELECT 1 FROM businesses WHERE invite_code = new_code) INTO code_exists;
    EXIT WHEN NOT code_exists;
  END LOOP;
  
  UPDATE businesses SET invite_code = new_code WHERE id = business_id;
  
  RETURN jsonb_build_object(
    'success', true,
    'invite_code', new_code
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- RLS POLICY FOR VIEWING INVITE CODES
-- ============================================================================

CREATE POLICY "Members can view business invite codes"
  ON businesses FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM business_members
      WHERE business_members.business_id = businesses.id
      AND business_members.user_id = auth.uid()
    )
  );
